development:
 
  stripe_publishable_key: <%= ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_TEST_SECRET_KEY'] %>
 
production:
  stripe_publishable_key: <%= ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_TEST_SECRET_KEY'] %>